// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxgvzkicuhackklhjjzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4Z3Z6a2ljdWhhY2trbGhqanpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTY4MjQsImV4cCI6MjA2Njc3MjgyNH0.PrVD8rGR_qmqM3_ogpkx3Nc9nKMh4PuwdHwkW_muPwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);